name: matthewc
favicon: null
layout_spectrum: 0.645421935711056
typography_spectrum: 0.8127469054888934
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.4536426260601729
  lightness: 0.3809313897509128
  saturation: 0.6851484207436442
  rhythmicContrast: 0.5760083098430187
purpose: []
